# Permalinks
permalink: pretty

# Base Site Settings
title: West Eleventh Media
email: westeleventhmedia@gmail.com
lang: en-us
description: >- # this means to ignore newlines until "baseurl:"
  A budding new media company based in Washington, D.C.
# twitter_username: jekyllrb
# github_username:  jekyll

# URLs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.westeleventh.media" # the base hostname & protocol for your site, e.g. http://example.com

# Collections
collections:
  newpodwhodis:
    output: true
    permalink: /newpodwhodis/:path/
    title: New Pod, Who Dis?
    email: newpodwhodis@gmail.com
    subtitle: Jackie, Joey, Jake, and Steven embark on a journey to discover the meaning of life
    summary: >-
      New Pod, Who Dis? is a weekly journey through the trials and tribulations of young adulthood. Your hosts Jackie,
      Joey, Jake, and Steven will engage in a spirited discussion of life's past, present, and future issues.
    image: /img/npwd_logo_feed.png

# Build settings
timezone: America/New_York
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.MD
  - _audio/
